# Generated by Django 3.2.4 on 2021-08-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0025_auto_20210806_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Producto')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('subcategoria', models.CharField(max_length=20, verbose_name='Subcategoria')),
                ('color', models.CharField(max_length=20, verbose_name='Color Producto')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Precio')),
                ('descripcion', models.TextField(max_length=20, verbose_name='Descripcion Producto')),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Cantidad')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='fotos', verbose_name='Fotografía Producto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
